import PageHeader, { H2, P, UL } from "@/components/ui/PageHeader";
import Callout, { K } from "@/components/ui/Callout";
import DataTable from "@/components/ui/DataTable";
import CodeBlock from "@/components/ui/CodeBlock";

export const metadata = {
  title: "PL/SQL — Triggers",
};

export default function SqlPlsqlTriggersPage() {
  return (
    <>
      <PageHeader
        eyebrow="Oracle SQL · PL/SQL"
        title="Triggers"
        description="BEFORE, AFTER, and INSTEAD OF triggers; INSERT/UPDATE/DELETE triggers; row-level versus statement-level; the :OLD and :NEW records; auditing triggers; and the mutating-table error with its fix."
        breadcrumbs={[{ label: "SQL" }, { label: "PL/SQL" }, { label: "Triggers" }]}
        updated="2026"
      />

      <P>
        A <strong>trigger</strong> is stored PL/SQL that fires automatically when a DML statement
        happens against a table — no application has to remember to call anything. That is their
        power and their risk: they run inside the same transaction, so every trigger error and every
        slow trigger is every insert/update/delete.
      </P>

      <H2>Timing and level</H2>
      <P>
        A trigger is defined by two independent axes, which combine into four classic kinds:
      </P>
      <DataTable
        headers={["", "BEFORE", "AFTER", "INSTEAD OF"]
        }
        rows={[
          ["ROW-level (FOR EACH ROW)", "Run per row, before the change — stamp/modify :NEW", "Run per row, after the change — audit/log", "Only valid on views — replace the DML the view cannot do"],
          ["STATEMENT-level (default)", "Run once for the whole statement, before", "Run once for the whole statement, after", "Only valid on views"],
        ]}
      />
      <CodeBlock
        language="sql"
        filename="The four knobs in one CREATE TRIGGER"
        code={`CREATE OR REPLACE TRIGGER trg_orders_audit
BEFORE INSERT OR UPDATE OR DELETE ON orders      -- the events
FOR EACH ROW                                      -- the level
BEGIN
  DBMS_OUTPUT.PUT_LINE('row touched');
END;
/`}
      />

      <H2>:OLD and :NEW</H2>
      <P>
        In a <strong>row-level</strong> trigger the record has two halves: <K>:OLD</K> holds the
        row's values before the change, <K>:NEW</K> after. What each <K>:</K> record contains depends
        on the event:
      </P>
      <DataTable
        headers={["Event", ":OLD", ":NEW"]
        }
        rows={[
          ["INSERT", "All NULL (no old row)", "The row being added"],
          ["UPDATE", "The pre-change row", "The post-change row (may be modified by the trigger)"],
          ["DELETE", "The row being removed", "All NULL"],
        ]}
      />
      <CodeBlock
        language="sql"
        filename="Inspect the before/after values"
        code={`CREATE OR REPLACE TRIGGER trg_orders_before
BEFORE INSERT OR UPDATE OF total_amount ON orders
FOR EACH ROW
BEGIN
  IF :NEW.total_amount > 0 AND :OLD.total_amount > 100000 THEN
    raise_application_error(-20010, 'Order value change too big');
  END IF;
END;
/`}
      />
      <Callout type="warning">
        A <K>BEFORE</K> row trigger can <em>change</em> <K>:NEW</K> to fix values before the row is
        written — the stamping pattern below. It cannot modify <K>:OLD</K>, and <K>AFTER</K> row
        triggers cannot change <K>:NEW</K> at all.
      </Callout>

      <H2>Auditing triggers</H2>
      <P>
        The most common real-world trigger: copy who/what/when into an audit table on every change
        (a lightweight alternative to full <K>AUDIT</K>, and a pattern Fusion-style apps rely on):
      </P>
      <CodeBlock
        language="sql"
        filename="A minimal audit trail"
        code={`CREATE TABLE customers_audit (
  aud_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER,
  old_limit   NUMBER(12,2),
  new_limit   NUMBER(12,2),
  action      VARCHAR2(6),
  changed_by  VARCHAR2(30),
  changed_at  TIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_customers_audit
AFTER UPDATE OR DELETE ON customers
FOR EACH ROW
BEGIN
  INSERT INTO customers_audit (customer_id, old_limit, new_limit, action,
                               changed_by, changed_at)
  VALUES (:OLD.customer_id, :OLD.credit_limit, :NEW.credit_limit,
          CASE WHEN :NEW.customer_id IS NULL THEN 'DELETE' ELSE 'UPDATE' END,
          USER, SYSTIMESTAMP);
END;
/`}
      />
      <Callout type="tip">
        Audit inside the <em>same transaction</em> means the audit row commits or rolls back with
        its source — that is usually the desired guarantee ("audit cannot lie"), but it also couples
        your audit write to every business transaction's performance.
      </Callout>

      <H2>Row-level vs statement-level — and the mutating-table error</H2>
      <P>
        <K>FOR EACH ROW</K> means per affected row; without it the trigger runs <em>once per
        statement</em>. Statement-level triggers cannot see <K>:OLD</K>/<K>:NEW</K>, which is also
        why they are the safe home for "after this whole batch, do X".
      </P>
      <Callout type="danger">
        The famous <strong><K>ORA-04091</K> mutating-table error</strong>: a <em>row-level</em>{" "}
        trigger on table T cannot query T itself ("ORA-04091: table T is mutating, trigger may not
        read or modify it"). While a row trigger runs, the table is in flux. The standard fixes:
        <UL>
          <li>Move the query to a <strong>statement-level AFTER trigger</strong> (which runs when the table is quiet) — read <K>:OLD</K>/<K>:NEW</K> only inside a row trigger, then aggregate there afterwards.</li>
          <li>Use a <strong>compound trigger</strong> (row-section + after-statement-section) to collect per-row data safely.</li>
        </UL>
      </Callout>
      <CodeBlock
        language="sql"
        filename="Compound trigger — the modern mutating-table escape"
        code={`CREATE OR REPLACE TRIGGER trg_orders_compound
FOR INSERT OR UPDATE ON orders
COMPOUND TRIGGER
  v_rows NUMBER := 0;

  AFTER EACH ROW IS
  BEGIN
    v_rows := v_rows + 1;            -- safe: just counting the row
  END AFTER EACH ROW;

  AFTER STATEMENT IS
  BEGIN
    -- the table is not mutating here — safe to query orders
    DBMS_OUTPUT.PUT_LINE('orders changed: ' || v_rows ||
                         ' — total now ' || total_order_count());
  END AFTER STATEMENT;
END trg_orders_compound;
/`}
      />

      <H2>INSTEAD OF triggers on views</H2>
      <P>
        A view is usually not updateable in complex cases. An <strong>INSTEAD OF</strong> trigger
        intercepts the DML on the view and lets you write the real implementation:
      </P>
      <CodeBlock
        language="sql"
        filename="Make a join view updateable by hand"
        code={`CREATE OR REPLACE TRIGGER trg_v_customers
INSTEAD OF INSERT ON v_customer_regions
FOR EACH ROW
BEGIN
  INSERT INTO customers (customer_id, customer_name, region_id)
  VALUES (:NEW.customer_id, :NEW.customer_name, :NEW.region_id);
END;
/`}
      />

      <H2>The production checklist</H2>
      <UL>
        <li><strong>Disable for bulk loads</strong> — triggers fire per row; a trillion-row load through a row trigger will not get faster.</li>
        <li><strong>Never hide DML-heavy logic in a trigger</strong> — it becomes invisible to every caller and every plan.</li>
        <li><strong>Name triggers</strong> and track them via <K>USER_TRIGGERS</K> — an unknown trigger is how "who changed that column" mysteries start.</li>
        <li>Use <K>ALTER TRIGGER … DISABLE/ENABLE</K> and optimizer hints like <K>NO_QUERY_TRANSFORMATION</K> deliberately, not as a habit.</li>
      </UL>
    </>
  );
}