import PageHeader, { H2, P, UL } from "@/components/ui/PageHeader";
import Callout, { K } from "@/components/ui/Callout";
import DataTable from "@/components/ui/DataTable";
import CodeBlock from "@/components/ui/CodeBlock";

export const metadata = {
  title: "Sequences & Identity Columns",
};

export default function SqlSequencesIdentityPage() {
  return (
    <>
      <PageHeader
        eyebrow="Oracle SQL · Database objects"
        title="Sequences & identity columns"
        description="CREATE SEQUENCE, NEXTVAL and CURRVAL, the CACHE/CYCLE/INCREMENT settings that bite you at scale, and the 12c+ identity columns that automate the whole pattern."
        breadcrumbs={[{ label: "SQL" }, { label: "Sequences & Identity" }]}
        updated="2026"
      />

      <P>
        Every table needs unique keys, and Oracle generates them with <strong>sequences</strong> —
        independent, concurrency-safe number generators. They are the classic pattern behind the
        primary key you have been seeing as <K>NUMBER PRIMARY KEY</K>. Since 12c, an{" "}
        <strong>identity column</strong> wires a sequence to a table automatically.
      </P>

      <H2>CREATE SEQUENCE and NEXTVAL / CURRVAL</H2>
      <CodeBlock
        language="sql"
        filename="Define a sequence, then use it"
        code={`CREATE SEQUENCE seq_orders
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

-- Ask for the next number: oracle assigns it, guaranteed unique
INSERT INTO orders (order_id, customer_id, total_amount)
VALUES (seq_orders.NEXTVAL, 42, 500);

-- Read the value THIS session just got (no call to NEXTVAL - it errors otherwise)
SELECT seq_orders.CURRVAL FROM dual;`}
      />
      <UL>
        <li>
          <K>NEXTVAL</K> gives the next number and moves the sequence forward;{" "}
          <K>CURRVAL</K> reads the last <K>NEXTVAL</K> your <em>session</em> fetched. Calling{" "}
          <K>CURRVAL</K> before any <K>NEXTVAL</K> raises <K>ORA-08002</K>.
        </li>
        <li>
          Sequences are <strong>gap-ok</strong>: rolled-back inserts, crashes, and <K>CACHE</K>{" "}
          changes all burn numbers. If you need truly gapless numbering you are in document
          sequencing territory (Oracle's DBMS-friendly "gapless" tools), not sequences.
        </li>
        <li>
          Because <K>NEXTVAL</K> is called during the statement, you can use it in an{" "}
          <K>INSERT ... SELECT</K> to number every row of the batch.
        </li>
      </UL>

      <H2>CACHE, CYCLE, INCREMENT — the settings that bite</H2>
      <DataTable
        headers={["Setting", "Default", "What it does", "Gotcha"]
        }
        rows={[
          ["INCREMENT", "1", "Step between numbers (negative counts down)", "Negative for descending IDs"],
          ["START WITH", "MINVALUE?", "First number returned", "Rarely needed after 12c identity"],
          ["CACHE", "20", "Pre-allocates numbers in memory for speed", "Gaps on instance-crash (numbers are lost, not reused)"],
          ["NOCACHE / ORDER", "", "No pre-allocation / guarantee of order across sessions", "ORDER costs performance on RAC"],
          ["CYCLE", "NOCYCLE", "Wrap around when MAXVALUE is hit", "CYCLE can duplicate IDs unless MINVALUE set carefully — usually avoid"],
          ["MAXVALUE", "10^27", "Upper boundary", "Overshoot throws ORA-08004 unless CYCLE"],
        ]}
      />
      <Callout type="warning">
        The two design decisions that matter: <strong>don't use CYCLE</strong> for primary keys
        (reused numbers silently collide with old rows), and keep <K>CACHE</K> moderate. A huge{" "}
        <K>CACHE</K> (e.g. 1,000) is great for bulk load speed but on an instance crash your key
        space jumps by that many unused numbers.
      </Callout>

      <H2>Identity columns (12c and later)</H2>
      <P>
        An <strong>identity column</strong> makes the sequence invisible — the database generates
        the value automatically on insert. It is now the recommended default for new tables' keys:
      </P>
      <CodeBlock
        language="sql"
        filename="GENERATED ALWAYS vs BY DEFAULT"
        code={`CREATE TABLE orders (
  order_id   NUMBER GENERATED BY DEFAULT AS IDENTITY
             PRIMARY KEY,          -- rows get 1,2,3... without any NEXTVAL
  customer_id NUMBER,
  total_amount NUMBER(12,2)
);

INSERT INTO orders (customer_id, total_amount) VALUES (42, 500);
-- order_id is filled for you (1, next 2, ...)`}
      />
      <DataTable
        headers={["Mode", "Behavior"]
        }
        rows={[
          ["GENERATED ALWAYS", "Insert can never supply the value; Oracle always generates it"],
          ["GENERATED BY DEFAULT", "Gives a value unless the INSERT explicitly provides one (good for data migration)"],
          ["BY DEFAULT ON NULL", "Like BY DEFAULT but also fills when the insert passes NULL"],
        ]}
      />
      <Callout type="info">
        Under the hood an identity column creates a sequence (look it up via{" "}
        <K>USER_TAB_IDENTITY_COLS</K>). The difference from doing it by hand: the tie to the table
        is automatic, so you cannot accidentally hand-number two tables from one shared sequence —
        the classic bug when you write the sequence pattern manually.
      </Callout>
      <P>
        For bulk imports that carry their own IDs (say, from the source system), use{" "}
        <K>BY DEFAULT</K> for the identity — an import can supply <K>order_id</K> and the database
        keeps generating fresh ones for everything new.
      </P>
    </>
  );
}